### PR TITLE
Hiera and Module Data Support

### PR DESCRIPTION
**Pull request by mloberg**
Added support for using module data and hiera for storing parameters for the module like pyenv prefix, user, pyenv version, and build environment variables.

Also added support for aliases.

### CODE REVIEW

**Comment by rgabo** [comment]
@mloberg do you plan to merge this PR? We're hitting #15 and wondering what's the least painful workaround is today... :smile: thanks

**Comment by mloberg** [comment]
@rgabo I'll merge it in tonight.

**Comment by rgabo** [comment]
@mloberg :pray: thank you!

**Comment by mloberg** [comment]
@rgabo If you need it sooner, you could always use `:git` and `:ref` in librarian.

```
mod 'puppet-python',
  :git => "https://github.com/mloberg/puppet-python.git",
  :ref => ''development"
```

**Comment by rgabo** [comment]
@mloberg, sure thing, that's what we're doing, but I wasn't sure whether this would get merged eventually and whether the project was maintained.

**Comment by mloberg** [comment]
@rgabo Release has been tagged at 3.0.0

**Comment by rgabo** [comment]
@mloberg thanks! cc @cu12

**Pull request merged**
